name: Node.js CI

# only trigger on pull request closed events
on:
  push:
    branches:
      - main
      - feature/SLNT-1_Initialize_extending_airbnb_config

jobs:
  package:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: echo "//npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN}}" >> ~/.npmrc
      - run: npm install
      - run: npm run build
      - run: npm publish