name: Node.js CI

# only trigger on pull request closed events
on:
  push:
    branches:
      - main
      - feature/SLNT-1_Initialize_extending_airbnb_config

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js latest
        uses: actions/setup-node@v3
        with:
          node-version: 'lts'

      - run: echo "//npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN}}" >> ~/.npmrc
      - run: npm install
      - run: npm run build
      - run: npm publish